name: "Push Notification"
on: [push, pull_request, create]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: vmiklos/notify-irc@8ae905b22a2d8d5098be886f71c6ab580ba6be79
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        with:
          channel: "#ged2dot-dev"
          nickname: github-ged2dot
          message: |
            ${{ toJson(github.event) }}
