name: "IRC Notification"
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: vmiklos/notify-irc@e929a7062f8f4061357b65ef9a089de11b6211dd
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        with:
          channel: "#ged2dot-dev"
          nickname: github-ged2dot
          message: |
            ${{ toJson(github.event) }}
